--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2023.03.01. 13:25:58
-- Server version: 5.5.5-10.4.21-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS halak;

CREATE DATABASE halak
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE halak;

--
-- Create table `species`
--
CREATE TABLE species (
  id INT(11) NOT NULL AUTO_INCREMENT,
  fishname VARCHAR(255) DEFAULT NULL,
  note INT(11) DEFAULT NULL,
  frequency VARCHAR(255) DEFAULT NULL,
  occurrence INT(11) DEFAULT NULL,
  protected BIT(1) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `landscapenames`
--
CREATE TABLE landscapenames (
  id INT(11) NOT NULL AUTO_INCREMENT,
  landscapename VARCHAR(50) DEFAULT NULL,
  specifiesid INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE landscapenames 
  ADD CONSTRAINT FK_landscapenames_species_id FOREIGN KEY (specifiesid)
    REFERENCES species(id);

--
-- Create table `users`
--
CREATE TABLE users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  firstname VARCHAR(255) DEFAULT NULL,
  lastname VARCHAR(255) DEFAULT NULL,
  gender VARCHAR(255) DEFAULT NULL,
  username VARCHAR(255) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  nuber INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

-- 
-- Dumping data for table species
--
-- Table halak.species does not contain any data (it is empty)

-- 
-- Dumping data for table users
--
-- Table halak.users does not contain any data (it is empty)

-- 
-- Dumping data for table landscapenames
--
-- Table halak.landscapenames does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;